/*
 * Novu API
 *
 * Novu REST API. Please see https://docs.novu.co/api-reference for more details.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@novu.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActivityStatsResponseDto {
    #[serde(rename = "weeklySent")]
    pub weekly_sent: f64,
    #[serde(rename = "monthlySent")]
    pub monthly_sent: f64,
}

impl ActivityStatsResponseDto {
    pub fn new(weekly_sent: f64, monthly_sent: f64) -> ActivityStatsResponseDto {
        ActivityStatsResponseDto {
            weekly_sent,
            monthly_sent,
        }
    }
}

