/*
 * Novu API
 *
 * Novu REST API. Please see https://docs.novu.co/api-reference for more details.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@novu.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActivityNotificationStepResponseDto {
    #[serde(rename = "_id")]
    pub _id: String,
    #[serde(rename = "active")]
    pub active: bool,
    #[serde(rename = "filters")]
    pub filters: Box<models::StepFilter>,
    #[serde(rename = "template", skip_serializing_if = "Option::is_none")]
    pub template: Option<serde_json::Value>,
}

// impl ActivityNotificationStepResponseDto {
//     pub fn new(_id: String, active: bool, filters: models::StepFilter) -> ActivityNotificationStepResponseDto {
//         ActivityNotificationStepResponseDto {
//             _id,
//             active,
//             filters: Box::new(filters),
//             template: None,
//         }
//     }
// }
