/*
 * Novu API
 *
 * Novu REST API. Please see https://docs.novu.co/api-reference for more details.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@novu.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddSubscribersRequestDto {
    /// List of subscriber identifiers that will be associated to the topic
    #[serde(rename = "subscribers")]
    pub subscribers: Vec<String>,
}

impl AddSubscribersRequestDto {
    pub fn new(subscribers: Vec<String>) -> AddSubscribersRequestDto {
        AddSubscribersRequestDto { subscribers }
    }
}
