/*
 * Novu API
 *
 * Novu REST API. Please see https://docs.novu.co/api-reference for more details.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@novu.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiKey {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "_userId")]
    pub _user_id: String,
}

impl ApiKey {
    pub fn new(key: String, _user_id: String) -> ApiKey {
        ApiKey { key, _user_id }
    }
}
