/*
 * Novu API
 *
 * Novu REST API. Please see https://docs.novu.co/api-reference for more details.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@novu.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkApplyChangeDto {
    #[serde(rename = "changeIds")]
    pub change_ids: Vec<String>,
}

impl BulkApplyChangeDto {
    pub fn new(change_ids: Vec<String>) -> BulkApplyChangeDto {
        BulkApplyChangeDto { change_ids }
    }
}
