/*
 * Novu API
 *
 * Novu REST API. Please see https://docs.novu.co/api-reference for more details.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@novu.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateWorkflowRequestDto {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "notificationGroupId")]
    pub notification_group_id: String,
    #[serde(rename = "notificationGroup", skip_serializing_if = "Option::is_none")]
    pub notification_group: Option<serde_json::Value>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "steps")]
    pub steps: Vec<models::NotificationStep>,
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    #[serde(rename = "draft", skip_serializing_if = "Option::is_none")]
    pub draft: Option<bool>,
    #[serde(rename = "critical", skip_serializing_if = "Option::is_none")]
    pub critical: Option<bool>,
    #[serde(rename = "preferenceSettings", skip_serializing_if = "Option::is_none")]
    pub preference_settings: Option<Box<models::PreferenceChannels>>,
    #[serde(rename = "blueprintId", skip_serializing_if = "Option::is_none")]
    pub blueprint_id: Option<String>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
}

impl CreateWorkflowRequestDto {
    pub fn new(name: String, notification_group_id: String, steps: Vec<models::NotificationStep>) -> CreateWorkflowRequestDto {
        CreateWorkflowRequestDto {
            name,
            notification_group_id,
            notification_group: None,
            tags: None,
            description: None,
            steps,
            active: None,
            draft: None,
            critical: None,
            preference_settings: None,
            blueprint_id: None,
            data: None,
        }
    }
}

