/*
 * Novu API
 *
 * Novu REST API. Please see https://docs.novu.co/api-reference for more details.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@novu.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateLayoutResponseDto {
    #[serde(rename = "_id")]
    pub _id: String,
}

impl CreateLayoutResponseDto {
    pub fn new(_id: String) -> CreateLayoutResponseDto {
        CreateLayoutResponseDto { _id }
    }
}
