/*
 * Novu API
 *
 * Novu REST API. Please see https://docs.novu.co/api-reference for more details.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@novu.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DelayScheduledMetadata {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "delayPath")]
    pub delay_path: String,
}

impl DelayScheduledMetadata {
    pub fn new(r#type: Type, delay_path: String) -> DelayScheduledMetadata {
        DelayScheduledMetadata {
            r#type,
            delay_path,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "scheduled")]
    Scheduled,
}

impl Default for Type {
    fn default() -> Type {
        Self::Scheduled
    }
}

