/*
 * Novu API
 *
 * Novu REST API. Please see https://docs.novu.co/api-reference for more details.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@novu.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditTranslationRequestDto {
    #[serde(rename = "fileName", skip_serializing_if = "Option::is_none")]
    pub file_name: Option<String>,
    #[serde(rename = "translation", skip_serializing_if = "Option::is_none")]
    pub translation: Option<String>,
}

impl EditTranslationRequestDto {
    pub fn new() -> EditTranslationRequestDto {
        EditTranslationRequestDto {
            file_name: None,
            translation: None,
        }
    }
}

