/*
 * Novu API
 *
 * Novu REST API. Please see https://docs.novu.co/api-reference for more details.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@novu.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FieldFilterPart {
    #[serde(rename = "field")]
    pub field: String,
    #[serde(rename = "value")]
    pub value: String,
    #[serde(rename = "operator")]
    pub operator: Operator,
    #[serde(rename = "on")]
    pub on: On,
}

impl FieldFilterPart {
    pub fn new(field: String, value: String, operator: Operator, on: On) -> FieldFilterPart {
        FieldFilterPart {
            field,
            value,
            operator,
            on,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Operator {
    #[serde(rename = "LARGER")]
    Larger,
    #[serde(rename = "SMALLER")]
    Smaller,
    #[serde(rename = "LARGER_EQUAL")]
    LargerEqual,
    #[serde(rename = "SMALLER_EQUAL")]
    SmallerEqual,
    #[serde(rename = "EQUAL")]
    Equal,
    #[serde(rename = "NOT_EQUAL")]
    NotEqual,
    #[serde(rename = "ALL_IN")]
    AllIn,
    #[serde(rename = "ANY_IN")]
    AnyIn,
    #[serde(rename = "NOT_IN")]
    NotIn,
    #[serde(rename = "BETWEEN")]
    Between,
    #[serde(rename = "NOT_BETWEEN")]
    NotBetween,
    #[serde(rename = "LIKE")]
    Like,
    #[serde(rename = "NOT_LIKE")]
    NotLike,
    #[serde(rename = "IN")]
    In,
}

impl Default for Operator {
    fn default() -> Operator {
        Self::Larger
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum On {
    #[serde(rename = "subscriber")]
    Subscriber,
    #[serde(rename = "payload")]
    Payload,
}

impl Default for On {
    fn default() -> On {
        Self::Subscriber
    }
}
