/*
 * Novu API
 *
 * Novu REST API. Please see https://docs.novu.co/api-reference for more details.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@novu.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMxRecordResponseDto {
    #[serde(rename = "mxRecordConfigured")]
    pub mx_record_configured: bool,
}

impl GetMxRecordResponseDto {
    pub fn new(mx_record_configured: bool) -> GetMxRecordResponseDto {
        GetMxRecordResponseDto {
            mx_record_configured,
        }
    }
}

