/*
 * Novu API
 *
 * Novu REST API. Please see https://docs.novu.co/api-reference for more details.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@novu.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupedBlueprintResponse {
    #[serde(rename = "general")]
    pub general: Vec<serde_json::Value>,
    #[serde(rename = "popular")]
    pub popular: serde_json::Value,
}

impl GroupedBlueprintResponse {
    pub fn new(general: Vec<serde_json::Value>, popular: serde_json::Value) -> GroupedBlueprintResponse {
        GroupedBlueprintResponse {
            general,
            popular,
        }
    }
}

