/*
 * Novu API
 *
 * Novu REST API. Please see https://docs.novu.co/api-reference for more details.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@novu.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarkAllMessageAsRequestDto {
    #[serde(rename = "feedIdentifier", skip_serializing_if = "Option::is_none")]
    pub feed_identifier: Option<models::MarkAllMessageAsRequestDtoFeedIdentifier>,
    /// Mark all subscriber messages as read, unread, seen or unseen
    #[serde(rename = "markAs")]
    pub mark_as: MarkAs,
}

impl MarkAllMessageAsRequestDto {
    pub fn new(
        feed_identifier: Option<models::MarkAllMessageAsRequestDtoFeedIdentifier>,
        mark_as: MarkAs,
    ) -> MarkAllMessageAsRequestDto {
        MarkAllMessageAsRequestDto {
            feed_identifier,
            mark_as,
        }
    }
}
/// Mark all subscriber messages as read, unread, seen or unseen
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MarkAs {
    #[serde(rename = "read")]
    Read,
    #[serde(rename = "seen")]
    Seen,
    #[serde(rename = "unread")]
    Unread,
    #[serde(rename = "unseen")]
    Unseen,
}

impl Default for MarkAs {
    fn default() -> MarkAs {
        Self::Read
    }
}
