/*
 * Novu API
 *
 * Novu REST API. Please see https://docs.novu.co/api-reference for more details.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@novu.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// MarkAllMessageAsRequestDtoFeedIdentifier : Optional feed identifier or array of feed identifiers
/// Optional feed identifier or array of feed identifiers
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MarkAllMessageAsRequestDtoFeedIdentifier {
    String(String),
    Array(Vec<String>),
}

impl Default for MarkAllMessageAsRequestDtoFeedIdentifier {
    fn default() -> Self {
        Self::String(Default::default())
    }
}
