/*
 * Novu API
 *
 * Novu REST API. Please see https://docs.novu.co/api-reference for more details.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@novu.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarkMessageAsRequestDto {
    #[serde(rename = "messageId")]
    pub message_id: Box<models::MarkMessageAsRequestDtoMessageId>,
    #[serde(rename = "mark")]
    pub mark: Box<models::MarkMessageFields>,
}

impl MarkMessageAsRequestDto {
    pub fn new(message_id: models::MarkMessageAsRequestDtoMessageId, mark: models::MarkMessageFields) -> MarkMessageAsRequestDto {
        MarkMessageAsRequestDto {
            message_id: Box::new(message_id),
            mark: Box::new(mark),
        }
    }
}

