/*
 * Novu API
 *
 * Novu REST API. Please see https://docs.novu.co/api-reference for more details.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@novu.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MemberInviteDto {
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "token")]
    pub token: String,
    #[serde(rename = "invitationDate")]
    pub invitation_date: String,
    #[serde(rename = "answerDate", skip_serializing_if = "Option::is_none")]
    pub answer_date: Option<String>,
    #[serde(rename = "_inviterId")]
    pub _inviter_id: String,
}
