/*
 * Novu API
 *
 * Novu REST API. Please see https://docs.novu.co/api-reference for more details.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@novu.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MemberUserDto {
    #[serde(rename = "_id")]
    pub _id: String,
    #[serde(rename = "firstName")]
    pub first_name: String,
    #[serde(rename = "lastName")]
    pub last_name: String,
    #[serde(rename = "email")]
    pub email: String,
}

impl MemberUserDto {
    pub fn new(_id: String, first_name: String, last_name: String, email: String) -> MemberUserDto {
        MemberUserDto {
            _id,
            first_name,
            last_name,
            email,
        }
    }
}
