/*
 * Novu API
 *
 * Novu REST API. Please see https://docs.novu.co/api-reference for more details.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@novu.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MessageResponseDtoContent {
    EmailBlock(Box<models::EmailBlock>),
    String(String),
}

impl Default for MessageResponseDtoContent {
    fn default() -> Self {
        Self::EmailBlock(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "text")]
    Text,
    #[serde(rename = "button")]
    Button,
}

impl Default for Type {
    fn default() -> Type {
        Self::Text
    }
}

