/*
 * Novu API
 *
 * Novu REST API. Please see https://docs.novu.co/api-reference for more details.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@novu.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotificationTrigger {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "identifier")]
    pub identifier: String,
    #[serde(rename = "variables")]
    pub variables: Vec<models::NotificationTriggerVariable>,
    #[serde(
        rename = "subscriberVariables",
        skip_serializing_if = "Option::is_none"
    )]
    pub subscriber_variables: Option<Vec<models::NotificationTriggerVariable>>,
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "event")]
    Event,
}

impl Default for Type {
    fn default() -> Type {
        Self::Event
    }
}
