/*
 * Novu API
 *
 * Novu REST API. Please see https://docs.novu.co/api-reference for more details.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@novu.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotificationStepVariant {
    #[serde(rename = "_id", skip_serializing_if = "Option::is_none")]
    pub _id: Option<String>,
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "_templateId", skip_serializing_if = "Option::is_none")]
    pub _template_id: Option<String>,
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    #[serde(rename = "shouldStopOnFail", skip_serializing_if = "Option::is_none")]
    pub should_stop_on_fail: Option<bool>,
    #[serde(rename = "template", skip_serializing_if = "Option::is_none")]
    pub template: Option<serde_json::Value>,
    #[serde(rename = "filters", skip_serializing_if = "Option::is_none")]
    pub filters: Option<Vec<models::StepFilter>>,
    #[serde(rename = "_parentId", skip_serializing_if = "Option::is_none")]
    pub _parent_id: Option<serde_json::Value>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Box<models::NotificationStepVariantMetadata>>,
    #[serde(rename = "replyCallback", skip_serializing_if = "Option::is_none")]
    pub reply_callback: Option<serde_json::Value>,
}

impl NotificationStepVariant {
    pub fn new() -> NotificationStepVariant {
        NotificationStepVariant {
            _id: None,
            uuid: None,
            name: None,
            _template_id: None,
            active: None,
            should_stop_on_fail: None,
            template: None,
            filters: None,
            _parent_id: None,
            metadata: None,
            reply_callback: None,
        }
    }
}

