/*
 * Novu API
 *
 * Novu REST API. Please see https://docs.novu.co/api-reference for more details.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@novu.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaginatedResponseDto<T> {
    /// The current page of the paginated response
    #[serde(rename = "page")]
    pub page: f64,
    /// Does the list have more items to fetch
    #[serde(rename = "hasMore")]
    pub has_more: bool,
    /// Number of items on each page
    #[serde(rename = "pageSize")]
    pub page_size: f64,
    /// The list of items matching the query
    #[serde(rename = "data")]
    pub data: Vec<T>,
}
