/*
 * Novu API
 *
 * Novu REST API. Please see https://docs.novu.co/api-reference for more details.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@novu.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Preference {
    /// Sets if the workflow is fully enabled for all channels or not for the subscriber.
    #[serde(rename = "enabled")]
    pub enabled: bool,
    /// Subscriber preferences for the different channels regarding this workflow
    #[serde(rename = "channels")]
    pub channels: Box<models::PreferenceChannels>,
}

impl Preference {
    pub fn new(enabled: bool, channels: models::PreferenceChannels) -> Preference {
        Preference {
            enabled,
            channels: Box::new(channels),
        }
    }
}
