/*
 * Novu API
 *
 * Novu REST API. Please see https://docs.novu.co/api-reference for more details.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@novu.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RenameTopicRequestDto {
    /// User defined custom name and provided by the user to rename the topic.
    #[serde(rename = "name")]
    pub name: String,
}

impl RenameTopicRequestDto {
    pub fn new(name: String) -> RenameTopicRequestDto {
        RenameTopicRequestDto { name }
    }
}
