/*
 * Novu API
 *
 * Novu REST API. Please see https://docs.novu.co/api-reference for more details.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@novu.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TopicSubscriberDto {
    #[serde(rename = "_organizationId")]
    pub _organization_id: String,
    #[serde(rename = "_environmentId")]
    pub _environment_id: String,
    #[serde(rename = "_subscriberId")]
    pub _subscriber_id: String,
    #[serde(rename = "_topicId")]
    pub _topic_id: String,
    #[serde(rename = "topicKey")]
    pub topic_key: String,
    #[serde(rename = "externalSubscriberId")]
    pub external_subscriber_id: String,
}

impl TopicSubscriberDto {
    pub fn new(_organization_id: String, _environment_id: String, _subscriber_id: String, _topic_id: String, topic_key: String, external_subscriber_id: String) -> TopicSubscriberDto {
        TopicSubscriberDto {
            _organization_id,
            _environment_id,
            _subscriber_id,
            _topic_id,
            topic_key,
            external_subscriber_id,
        }
    }
}

