/*
 * Novu API
 *
 * Novu REST API. Please see https://docs.novu.co/api-reference for more details.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@novu.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TopicPayloadDto {
    #[serde(rename = "topicKey")]
    pub topic_key: String,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl TopicPayloadDto {
    pub fn new(topic_key: String, r#type: Type) -> TopicPayloadDto {
        TopicPayloadDto { topic_key, r#type }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "Subscriber")]
    Subscriber,
    #[serde(rename = "Topic")]
    Topic,
}

impl Default for Type {
    fn default() -> Type {
        Self::Subscriber
    }
}
