/*
 * Novu API
 *
 * Novu REST API. Please see https://docs.novu.co/api-reference for more details.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@novu.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TranslationGroupResponseDto {
    #[serde(rename = "_id")]
    pub _id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "identifier")]
    pub identifier: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "_environmentId")]
    pub _environment_id: String,
    #[serde(rename = "_organizationId")]
    pub _organization_id: String,
}

impl TranslationGroupResponseDto {
    pub fn new(
        _id: String,
        name: String,
        identifier: String,
        created_at: String,
        updated_at: String,
        _environment_id: String,
        _organization_id: String,
    ) -> TranslationGroupResponseDto {
        TranslationGroupResponseDto {
            _id,
            name,
            identifier,
            created_at,
            updated_at,
            _environment_id,
            _organization_id,
        }
    }
}
