/*
 * Novu API
 *
 * Novu REST API. Please see https://docs.novu.co/api-reference for more details.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@novu.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TranslationResponseDto {
    #[serde(rename = "_id")]
    pub _id: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "_environmentId")]
    pub _environment_id: String,
    #[serde(rename = "_organizationId")]
    pub _organization_id: String,
    #[serde(rename = "_groupId")]
    pub _group_id: String,
    #[serde(rename = "isoLanguage")]
    pub iso_language: String,
    #[serde(rename = "translations")]
    pub translations: String,
    #[serde(rename = "fileName")]
    pub file_name: String,
}

impl TranslationResponseDto {
    pub fn new(_id: String, created_at: String, updated_at: String, _environment_id: String, _organization_id: String, _group_id: String, iso_language: String, translations: String, file_name: String) -> TranslationResponseDto {
        TranslationResponseDto {
            _id,
            created_at,
            updated_at,
            _environment_id,
            _organization_id,
            _group_id,
            iso_language,
            translations,
            file_name,
        }
    }
}

