/*
 * Novu API
 *
 * Novu REST API. Please see https://docs.novu.co/api-reference for more details.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@novu.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// TriggerEventRequestDtoTenant : It is used to specify a tenant context during trigger event.     If a new tenant object is provided, we will create a new tenant.     
/// It is used to specify a tenant context during trigger event.     If a new tenant object is provided, we will create a new tenant.     
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TriggerEventRequestDtoTenant {
    /// Unique identifier of a tenant in your system
    String(String),
    TenantPayloadDto(Box<models::TenantPayloadDto>),
}

impl Default for TriggerEventRequestDtoTenant {
    fn default() -> Self {
        Self::String(Default::default())
    }
}
