/*
 * Novu API
 *
 * Novu REST API. Please see https://docs.novu.co/api-reference for more details.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@novu.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnseenCountResponse {
    #[serde(rename = "count")]
    pub count: f64,
}

impl UnseenCountResponse {
    pub fn new(count: f64) -> UnseenCountResponse {
        UnseenCountResponse { count }
    }
}
