/*
 * Novu API
 *
 * Novu REST API. Please see https://docs.novu.co/api-reference for more details.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@novu.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateWorkflowOverrideRequestDto {
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    #[serde(rename = "preferenceSettings", skip_serializing_if = "Option::is_none")]
    pub preference_settings: Option<Box<models::PreferenceChannels>>,
}

impl UpdateWorkflowOverrideRequestDto {
    pub fn new() -> UpdateWorkflowOverrideRequestDto {
        UpdateWorkflowOverrideRequestDto {
            active: None,
            preference_settings: None,
        }
    }
}

