/*
 * Novu API
 *
 * Novu REST API. Please see https://docs.novu.co/api-reference for more details.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@novu.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateSubscriberPreferenceResponseDto {
    /// The workflow information and if it is critical or not
    #[serde(rename = "template")]
    pub template: Box<models::TemplateResponse>,
    /// The preferences of the subscriber regarding the related workflow
    #[serde(rename = "preference")]
    pub preference: Box<models::Preference>,
}

impl UpdateSubscriberPreferenceResponseDto {
    pub fn new(template: models::TemplateResponse, preference: models::Preference) -> UpdateSubscriberPreferenceResponseDto {
        UpdateSubscriberPreferenceResponseDto {
            template: Box::new(template),
            preference: Box::new(preference),
        }
    }
}

