/*
 * Novu API
 *
 * Novu REST API. Please see https://docs.novu.co/api-reference for more details.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@novu.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VariablesResponseDto {
    #[serde(rename = "translations")]
    pub translations: serde_json::Value,
    #[serde(rename = "system")]
    pub system: serde_json::Value,
}

impl VariablesResponseDto {
    pub fn new(translations: serde_json::Value, system: serde_json::Value) -> VariablesResponseDto {
        VariablesResponseDto {
            translations,
            system,
        }
    }
}

