/*
 * Novu API
 *
 * Novu REST API. Please see https://docs.novu.co/api-reference for more details.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@novu.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowsResponseDto {
    #[serde(rename = "totalCount")]
    pub total_count: f64,
    #[serde(rename = "data")]
    pub data: Vec<models::WorkflowResponse>,
    #[serde(rename = "pageSize")]
    pub page_size: f64,
    #[serde(rename = "page")]
    pub page: f64,
}

impl WorkflowsResponseDto {
    pub fn new(total_count: f64, data: Vec<models::WorkflowResponse>, page_size: f64, page: f64) -> WorkflowsResponseDto {
        WorkflowsResponseDto {
            total_count,
            data,
            page_size,
            page,
        }
    }
}

